# Generated by Django 5.2.6 on 2025-10-02 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurpriseBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Например: 'Сюрприз бокс от Osh Markazi'", max_length=200)),
                ('description', models.TextField(help_text='Описание того, что может быть в боксе')),
                ('box_type', models.CharField(choices=[('mixed', 'Смешанный бокс'), ('bakery', 'Хлебобулочные изделия'), ('meals', 'Готовые блюда'), ('groceries', 'Продукты'), ('desserts', 'Десерты'), ('beverages', 'Напитки')], default='mixed', max_length=20)),
                ('original_value', models.DecimalField(decimal_places=2, help_text='Общая стоимость товаров в боксе', max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='Цена продажи бокса', max_digits=10)),
                ('total_quantity', models.PositiveIntegerField(default=1, help_text='Сколько боксов доступно')),
                ('reserved_quantity', models.PositiveIntegerField(default=0)),
                ('sold_quantity', models.PositiveIntegerField(default=0)),
                ('available_from', models.DateTimeField(help_text='С какого времени доступен бокс')),
                ('available_until', models.DateTimeField(help_text='До какого времени доступен бокс')),
                ('pickup_start', models.TimeField(help_text='Время начала самовывоза')),
                ('pickup_end', models.TimeField(help_text='Время окончания самовывоза')),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold_out', 'Sold Out'), ('expired', 'Expired')], default='available', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='surprise_boxes/')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surprise_boxes', to='vendors.branch')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surprise_boxes', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'Сюрприз бокс',
                'verbose_name_plural': 'Сюрприз боксы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurpriseBoxItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Количество этого товара в боксе')),
                ('notes', models.CharField(blank=True, help_text='Дополнительные заметки о товаре', max_length=200)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.item')),
                ('surprise_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.surprisebox')),
            ],
            options={
                'verbose_name': 'Товар в сюрприз боксе',
                'verbose_name_plural': 'Товары в сюрприз боксе',
                'unique_together': {('surprise_box', 'item')},
            },
        ),
        migrations.AddField(
            model_name='surprisebox',
            name='items',
            field=models.ManyToManyField(related_name='surprise_boxes', through='catalog.SurpriseBoxItem', to='catalog.item'),
        ),
    ]
