# Generated by Django 5.2.4 on 2025-10-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_surprisebox_surpriseboxitem_surprisebox_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surprisebox',
            name='pickup_end',
            field=models.TimeField(blank=True, help_text='Время окончания самовывоза', null=True),
        ),
        migrations.AlterField(
            model_name='surprisebox',
            name='pickup_start',
            field=models.TimeField(blank=True, help_text='Время начала самовывоза', null=True),
        ),
    ]
