# Generated by Django 5.2.4 on 2025-10-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_surprisebox_pickup_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Срок годности товара', null=True),
        ),
    ]
